spring:
    application:
        name: Funds Application
    datasource:
    	driverClassName: Driver: com.microsoft.jdbc.sqlserver.SQLServerDriver
        url: jdbc:microsoft:sqlserver://localhost:8080/WmnsfFunds
        username: fundsapp
        password: password12345
    view:
        prefix: /WEB-INF/templates/
        suffix: .jsp

security:
    basic:
        enabled: false

jpa:
	database-platform: org.hibernate.dialect.SQLServer2008Dialect
    hibernate:
        ddl-auto: update

#spring.datasource.url=jdbc:microsoft://localhost/sfcbdb
#spring.datasource.username=root
#spring.datasource.password=mssql
#spring.datasource.driver-class-name=com.microsoft.jdbc.Driver
#spring.view.prefix=/WEB-INF/templates/
#spring.view.suffix=.jsp