spring:
    application:
        name: Funds Application
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/WmnsfFunds
        username: fundsapp
        password: password12345
    view:
        prefix: /WEB-INF/templates/
        suffix: .jsp

security:
    basic:
        enabled: false

jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
        ddl-auto: update

#spring.datasource.url=jdbc:mysql://localhost/sfcbdb
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.view.prefix=/WEB-INF/templates/
#spring.view.suffix=.jsp